In [49]:
import torch
import torch.nn as nn

vocab_size = 10
seq_len = 5
d_model = 5
pe = torch.rand(seq_len, d_model)
print(pe.shape)  # Output: torch.Size([100, 512])

torch.Size([5, 5])


In [50]:
print(pe)

tensor([[0.8674, 0.5577, 0.3518, 0.7617, 0.4355],
        [0.2657, 0.7415, 0.7800, 0.2903, 0.4936],
        [0.2515, 0.4729, 0.1520, 0.1872, 0.8397],
        [0.1066, 0.2644, 0.4080, 0.4840, 0.9861],
        [0.6545, 0.6932, 0.5360, 0.4239, 0.7800]])


In [55]:
pe[:,0::2]

tensor([[0.8674, 0.3518, 0.4355],
        [0.2657, 0.7800, 0.4936],
        [0.2515, 0.1520, 0.8397],
        [0.1066, 0.4080, 0.9861],
        [0.6545, 0.5360, 0.7800]])

In [57]:
pe.shape

torch.Size([5, 5])

In [44]:
#apply the sin to even indices and cos to odd indices
pe[:, 0::2] = torch.sin(position * div_term)  # Shape: (seq_len, d_model/2)
pe[:, 1::2] = torch.cos(position * div_term)  # Shape: (seq_len, d_model/2)

# Add a batch dimension to the positional encodings
pe = pe.unsqueeze(0)  # Shape: (1, seq_len, d_model)

NameError: name 'div_term' is not defined

In [39]:
position = torch.arange(0, seq_len).unsqueeze(1)

In [35]:
print(position.ndim)
print(position.shape)
print(position)

2
torch.Size([5, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])


In [36]:
position = torch.arange(0, seq_len).squeeze(-1)

In [37]:
print(position.ndim)
print(position.shape)
print(position)

1
torch.Size([5])
tensor([0, 1, 2, 3, 4])


In [43]:
emb = nn.Embedding(vocab_size, d_model) 
print(emb.weight.shape)  # Output: torch.Size([vocab_size, d_model])
print(emb.weight)

torch.Size([10, 5])
Parameter containing:
tensor([[-1.1329,  1.8434, -0.4108, -0.9262, -0.5970],
        [ 0.2009,  1.2285,  0.3854, -0.7645, -0.0177],
        [ 0.0475,  1.1438,  0.4119, -2.1207, -1.8532],
        [ 1.6544, -0.7456, -2.2872,  0.8947,  0.7146],
        [-0.2865,  0.8356, -0.4646,  0.8691,  0.0775],
        [ 1.6546,  1.9735, -0.8713, -0.5394, -0.6261],
        [-0.1090, -0.4066, -0.9871, -0.2179, -2.4558],
        [ 0.1311, -1.0188, -0.6426,  0.4382,  1.4282],
        [-0.4830, -0.0724,  0.2021, -0.8166, -1.1088],
        [-0.9550,  1.8964,  0.0170, -0.2265, -0.8328]], requires_grad=True)
